[package]
name = "km-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1"
ignore = "0.4"
jwalk = "0.8"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
